version: "3.1"
services:
  db:
    image: mariadb
    container_name: m183_mariadb
    ports:
      - 3306:3306
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: zli123
    volumes:
      - ./database:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: m183_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 80:80
    volumes:
      - /sessions
    links:
      - db